version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "01:00"
  open-pull-requests-limit: 10
  target-branch: feature/templates
  ignore:
  - dependency-name: "@vue/test-utils"
    versions:
    - 1.1.2
    - 1.1.3
  - dependency-name: "@vue/cli-plugin-babel"
    versions:
    - 4.5.11
  - dependency-name: elliptic
    versions:
    - 6.5.3
  - dependency-name: handlebars
    versions:
    - 4.7.6
